const gigs = [
	{
		Date: "Saturday, April 17, 2021",
		Time: "5:00pm - 7:00pm",
		Location: "The Village of Rochester Hills (Fountain)",
		Details: "Musical entertainment"
	},
	{
		Date: "Saturday, May 29, 2021",
		Time: "5:00pm - 7:00pm",
		Location: "The Village of Rochester Hills (Fountain)",
		Details: "Musical entertainment"
	},
	{
		Date: "Saturday 2/20/2021",
		Time: "5:00pm - 7:00pm",
		Location: "The Village of Rochester Hills (Fire Pit)",
		Details: "Musical Entertainment",
	},
	{
		Date: "Saturday 1/30/2021",
		Time: "5:00pm - 7:00pm",
		Location: "The Village of Rochester Hills (Fire Pit)",
		Details: "Musical Entertainment",
	},
	{
		Date: "Saturday 1/2/2021",
		Time: "5:00pm - 7:00pm",
		Location: "The Village of Rochester Hills (Fire Pit)",
		Details: "Musical Entertainment",
	},
	{
		Date: "Wednesday 12/23/2020",
		Time: "5:00pm - 7:00pm",
		Location: "The Village of Rochester Hills (Fire Pit)",
		Details: "Christmas Music",
	},
	{
		Date: "Thursday 12/17/2020",
		Time: "5:00pm - 7:00pm",
		Location: "The Village of Rochester Hills (Fire Pit)",
		Details: "Christmas Music",
	},
	{
		Date: "Wednesday 12/16/2020",
		Time: "10:30am",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy - CANCELED",
	},
	{
		Date: "Saturday 12/12/2020",
		Time: "5:00pm - 7:00pm",
		Location: "The Village of Rochester Hills (Fire Pit)",
		Details: "Christmas Music",
	},
	{
		Date: "Friday 12/11/2020",
		Time: "4:30pm - 6:30pm",
		Location: "The Village of Rochester Hills (In Front of Chico's)",
		Details: "Christmas Music",
	},
	{
		Date: "Thursday 12/10/2020",
		Time: "4:30pm - 6:30pm",
		Location: "The Village of Rochester Hills (In Front of Chico's)",
		Details: "Christmas Music",
	},
	{
		Date: "Saturday 12/5/2020",
		Time: "5:00pm - 7:00pm",
		Location: "The Village of Rochester Hills (Fire Pit)",
		Details: "Christmas Music",
	},
	{
		Date: "Saturday 11/28/2020",
		Time: "5:00pm - 7:00pm",
		Location: "The Village of Rochester Hills (Fire Pit)",
		Details: "Christmas Music",
	},
	{
		Date: "Friday 11/27/2020",
		Time: "6:00pm - 8:00pm",
		Location: "The Village of Rochester Hills (Fire Pit)",
		Details: "Christmas Music",
	},
	{
		Date: "Wednesday 11/18/2020",
		Time: "10:30am",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy - CANCELED",
	},
	{
		Date: "Wednesday 10/21/2020",
		Time: "10:30am",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy - CANCELED",
	},
	{
		Date: "Saturday 10/3/2020",
		Time: "",
		Location: "Port Huron",
		Details: "David Thomas & Co. - Wedding Cocktail Hour and Reception",
	},
	{
		Date: "Wednesday 9/16/2020",
		Time: "10:30am",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy - CANCELED",
	},
	{
		Date: "Saturday 9/5/2020",
		Time: "5:00pm - 7:00pm",
		Location: "The Village of Rochester Hills Gazebo",
		Details:
			"David Thomas &amp; Co. - Summer Concert Series (Labor Day Weekend)",
	},
	{
		Date: "Friday 8/28/2020",
		Time: "5:00pm - 7:00pm",
		Location: "The Village of Rochester Hills Gazebo",
		Details: "David Thomas &amp; Co. (Duo) - Summer Concert Series",
	},
	{
		Date: "Saturday 8/22/2020",
		Time: "5:00pm - 7:00pm",
		Location: "The Village of Rochester Hills Gazebo",
		Details: "David Thomas &amp; Co. - Summer Concert Series",
	},
	{
		Date: "Wednesday 8/19/2020",
		Time: "10:30am",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy - CANCELED",
	},
	{
		Date: "Friday 7/31/2020",
		Time: "5:00pm - 7:00pm",
		Location: "The Village of Rochester Hills Gazebo",
		Details: "David Thomas (Solo) - Summer Concert Series",
	},
	{
		Date: "Friday 7/24/2020",
		Time: "7:00pm - 11:00pm",
		Location: "Addison Oaks, Leonard, MI",
		Details: "Jazz Quartet with Sean Mallare - Special Event",
	},
	{
		Date: "Saturday 7/18/2020",
		Time: "5:00pm - 7:00pm",
		Location: "The Village of Rochester Hills Gazebo",
		Details: "David Thomas &amp; Co. - Summer Concert Series",
	},
	{
		Date: "Wednesday 7/15/2020",
		Time: "10:30am",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy - CANCELED",
	},
	{
		Date: "Wednesday 7/8/2020",
		Time: "5:30pm",
		Location: "Residence in Rochester Hills",
		Details: "David Thomas &amp; Co. (Duo) - Fundraiser",
	},
	{
		Date: "Wednesday 6/17/2020",
		Time: "10:30am",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy - CANCELED",
	},
	{
		Date: "Wednesday 5/20/2020",
		Time: "10:30am",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy - CANCELED",
	},
	{
		Date: "Friday 5/8/2020",
		Time: "",
		Location: "MI",
		Details: "Trumpet with SpaceCat for Wedding - CANCELED",
	},
	{
		Date: "Wednesday 4/15/2020",
		Time: "10:30am",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy - CANCELED",
	},
	{
		Date: "Wednesday 4/1/2020",
		Time: "7:00pm",
		Location: "Good Shepherd Lutheran Church",
		Details: "Piano for service - CANCELED",
	},
	{
		Date: "Wednesday 3/18/2020",
		Time: "10:30am",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy - CANCELED",
	},
	{
		Date: "Wednesday 3/18/2020",
		Time: "7:00pm",
		Location: "Good Shepherd Lutheran Church",
		Details: "Piano for service - CANCELED",
	},
	{
		Date: "Wednesday 3/4/2020",
		Time: "7:00pm",
		Location: "Good Shepherd Lutheran Church",
		Details: "Piano for service",
	},
	{
		Date: "Wednesday 2/19/2020",
		Time: "10:30am",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy",
	},
	{
		Date: "Thursday 1/23/2020",
		Time: "8:00pm - 12:00am",
		Location: "Cliff Bell's, Detroit, MI",
		Details: "David Thomas &amp; Co. (trio)",
	},
	{
		Date: "Wednesday 1/15/2020",
		Time: "10:30am",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy",
	},
	{
		Date: "Wednesday 12/18/2019",
		Time: "7:00pm",
		Location: "Good Shepherd Lutheran Church",
		Details: "Piano for service",
	},
	{
		Date: "Tuesday 12/17/2019",
		Time: "6:30pm",
		Location: "River Crest, Rochester Hills, MI",
		Details:
			"Piano and Vocals with Justin Jozwiak for Cane and Able Stroke Recovery Group",
	},
	{
		Date: "Saturday 12/14/2019",
		Time: "6:30pm - 8:00pm",
		Location: "The Scarab Club, Detroit, MI",
		Details: "Boar's Head Corporate Christmas Party with Sam Copperman",
	},
	{
		Date: "Wednesday 12/11/2019",
		Time: "7:00pm",
		Location: "Good Shepherd Lutheran Church",
		Details: "Piano for service",
	},
	{
		Date: "Tuesday 12/10/2019",
		Time: "4:45pm",
		Location: "Cliff Bell's, Detroit, MI",
		Details:
			"Vocals, piano, and trumpet for private Christmas party with Cory Allen",
	},
	{
		Date: "Friday 12/6/2019",
		Time: "10:30am - 12:00pm",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy",
	},
	{
		Date: "Tuesday 12/3/2019",
		Time: "",
		Location: "Addison Oaks, Leonard, MI",
		Details:
			"David Thomas &amp; Co. (Duo) for Meadowbrook Women's Club Holiday Dinner",
	},
	{
		Date: "Friday 11/22/2019",
		Time: "6:00pm - 9:00pm",
		Location: "The Village of Rochester Hills",
		Details:
			'David Thomas &amp; Co.; "Light the Village" tree lighting and Santa coming to town ceremony',
	},
	{
		Date: "Wednesday 11/20/2019",
		Time: "10:30am - 12:00pm",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy",
	},
	{
		Date: "Saturday 11/16/2019",
		Time: "6:00pm - 11:00pm",
		Location: "The Inn at St. John's, Plymouth, MI",
		Details: "Piano with jazz quartet for wedding rehearsal dinner",
	},
	{
		Date: "Wednesday 10/16/2019",
		Time: "10:30am - 12:00pm",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy",
	},
	{
		Date: "Sunday 10/13/2019",
		Time: "3:00pm",
		Location: "Avon Tower, Rochester Hills, MI",
		Details: "Piano and vocals for 97th birthday party",
	},
	{
		Date: "Saturday 10/12/2019",
		Time: "11:30am",
		Location: "Sterling Heights, MI",
		Details: "Friends Supporting Parents Service of Remembrance",
	},
	{
		Date: "Thursday 9/19/2019",
		Time: "8:00pm - 12:00pm",
		Location: "Cliff Bell's, Detroit, MI",
		Details: "David Thomas &amp; Co. (trio)",
	},
	{
		Date: "Wednesday 9/18/2019",
		Time: "10:30am - 12:00pm",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy",
	},
	{
		Date: "Sunday 9/15/2019",
		Time: "3:00pm",
		Location: "Greystone Golf Club, Washington, MI",
		Details: "Solo Piano for Wedding and Cocktail Hour",
	},
	{
		Date: "Monday 9/2/2019",
		Time: "11:00am",
		Location: "Samaritas Senior Living, Bloomfield Hills, MI",
		Details: "Solo Piano for Labor Day Buffet",
	},
	{
		Date: "Thursday 8/22/2019",
		Time: "5:00pm",
		Location: "Samaritas Senior Living, Bloomfield Hills, MI",
		Details: "Solo Piano for Open House",
	},
	{
		Date: "Wednesday 8/21/2019",
		Time: "10:30am - 12:00pm",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy",
	},
	{
		Date: "Saturday 8/10/2019",
		Time: "7:00pm",
		Location: "Shinola Hotel, Detroit, MI",
		Details: "Piano with Jazz Trio for Wedding",
	},
	{
		Date: "Wednesday 8/7/2019",
		Time: "7:00pm - 10:00pm",
		Location: "Penny Black Grill &amp; Tap, Rochester, MI",
		Details: "Piano and Vocals on the Patio",
	},
	{
		Date: "Saturday 7/27/2019",
		Time: "2:00pm - 6:00pm",
		Location: " Orchard Lake Fine Art Show, West Bloomfield Township, MI",
		Details: "Piano, Trumpet, and Vocals with Sheila Landis (Duo)",
	},
	{
		Date: "Sunday 7/21/2019",
		Time: "2:45pm",
		Location: " Michigan Jazz Festival, Schoolcraft College, Livonia, MI",
		Details: "Piano with Camille Price (duo)",
	},
	{
		Date: "Wednesday 7/17/2019",
		Time: "10:30am - 12:00pm",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy",
	},
	{
		Date: "Thursday 6/27/2019",
		Time: "6:30pm - 9:00pm",
		Location: "Brookedale Woods Subdivision, Rochester Hills, MI",
		Detail:
			"David Thomas &amp; Co. (trio); Concert in the Park on Raintree Drive",
	},
	{
		Date: "Wednesday 6/19/2019",
		Time: "10:30am - 12:00pm",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy",
	},
	{
		Date: "Tuesday 6/18/2019",
		Time: "6:00pm - 10:30pm",
		Location: "Meadow Brook Hall, Rochester Hills, MI",
		Details: "Corporate Event; Piano with Jazz Trio",
	},
	{
		Date: "Sunday 6/16/2019",
		Time: "2:00pm - 4:00pm",
		Location: "Grosse Pointe Congregational Church",
		Details: "Art Gallery Opening; Piano and vocals with Camille Price",
	},
	{
		Date: "Sunday 5/19/2019",
		Time: "1:00pm",
		Location: "Twin Lakes Golf Course, Oakland Township, MI",
		Details: "Piano and vocals for Memorial Service",
	},
	{
		Date: "Wednesday 5/15/2019",
		Time: "2:00pm - 4:00pm",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy",
	},
	{
		Date: "Saturday 5/4/2019",
		Time: "",
		Location: "St. Irenaeus Catholic Church",
		Details: "Solo piano for Church Appreciation Dinner",
	},
	{
		Date: "Friday 5/3/2019",
		Time: "9:00am",
		Location: "Ojibwa Elementary School, Macomb, MI",
		Details: "Piano and trumpet with jazz combo; concert for school",
	},
	{
		Date: "Tuesday 4/23/2019",
		Time: "",
		Location: "River Crest, Rochester Hills, MI",
		Details: "Piano and vocals with Justin Jozwiak for Anniversary Party",
	},
	{
		Date: "Wednesday 4/17/2019",
		Time: "2:00pm - 4:00pm",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy",
	},
	{
		Date: "Sunday 4/14/2019",
		Time: "12:00pm - 3:00pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Piano and vocals with James O'Donnell",
	},
	{
		Date: "Friday 4/12/2019",
		Time: "5:00pm",
		Location: "1st United Methodist Church, Royal Oak, MI",
		Details: "Organ with Dave Huber for Fish Fry",
	},
	{
		Date: "Sunday 4/7/2019",
		Time: "12:00pm - 3:00pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Piano and vocals with James O'Donnell",
	},
	{
		Date: "Sunday 3/31/2019",
		Time: "11:30pm - 2:30pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Piano and vocals with James O'Donnell",
	},
	{
		Date: "Sunday 3/24/2019",
		Time: "11:00am - 2:00pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Piano and vocals with James O'Donnell",
	},
	{
		Date: "Wednesday 3/20/2019",
		Time: "2:00pm - 4:00pm",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy",
	},
	{
		Date: "Sunday 3/17/2019",
		Time: "12:00pm - 3:00pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Piano and vocals with James O'Donnell",
	},
	{
		Date: "Sunday 3/10/2019",
		Time: "12:00pm - 3:00pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Piano and vocals with James O'Donnell",
	},
	{
		Date: "Sunday 3/3/2019",
		Time: "12:00pm - 3:00pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Piano and vocals with James O'Donnell",
	},
	{
		Date: "Sunday 2/24/2019",
		Time: "11:30pm - 2:30pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Piano and vocals with James O'Donnell",
	},
	{
		Date: "Saturday 2/23/2019",
		Time: "5:30pm - 9:00pm",
		Location: "Pine Knob Mansion, Clarkston, MI",
		Details: "Wedding Cocktail Hour and Dinner",
	},
	{
		Date: "Wednesday 2/20/2019",
		Time: "2:00pm - 4:00pm",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy",
	},
	{
		Date: "Sunday 2/17/2019",
		Time: "12:00pm - 3:00pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Piano and vocals with James O'Donnell",
	},
	{
		Date: "Sunday 2/10/2019",
		Time: "12:00pm - 3:00pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Piano and vocals with James O'Donnell",
	},
	{
		Date: "Sunday 1/27/2019",
		Time: "11:30pm - 2:30pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Piano and vocals with James O'Donnell",
	},
	{
		Date: "Monday 1/21/2019",
		Time: "",
		Location: "American Polish Century Club, Sterling Heights, MI",
		Details: "Piano with The Coachmen",
	},
	{
		Date: "Sunday 1/20/2019",
		Time: "12:00pm - 3:00pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Piano and vocals with James O'Donnell",
	},
	{
		Date: "Thursday 1/17/2019",
		Time: "8:00pm - 12:00pm",
		Location: "Cliff Bell's, Detroit, MI",
		Details: "David Thomas &amp; Co. (trio)",
	},
	{
		Date: "Wednesday 1/16/2019",
		Time: "2:00pm - 4:00pm",
		Location: "IHM Sisters Motherhouse, Monroe, MI",
		Details: "Music Therapy",
	},
	{
		Date: "Sunday 1/13/2019",
		Time: "12:00pm - 3:00pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Piano and vocals with James O'Donnell",
	},
	{
		Date: "Sunday 1/6/2019",
		Time: "12:00pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Piano and vocals with James O'Donnell",
	},
	{
		Date: "Sunday 12/30/2018",
		Time: "1:00pm",
		Location: "Assumption Grotto Church, Detroit, MI",
		Details: "David Thomas &amp; Co. (trio), Little Marian Sons Fundraiser",
	},
	{
		Date: "Sunday 12/23/2018",
		Time: "11:00am - 2:00pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Keyboard and vocals with James O'Donnell",
	},
	{
		Date: "Thursday 12/20/2018",
		Time: "8:00pm",
		Location: "Cadieux Cafe, Detroit, MI",
		Details: "Trumpet with Planet D Nonet, Christmas Party",
	},
	{
		Date: "Wednesday 12/19/2018",
		Time: "2:00pm",
		Location: "IHM Sisters, Monroe, MI",
		Detail:
			"Solo Piano, Vocals, Trumpet, Flute, Piccolo; Private Event for Residents",
	},
	{
		Date: "Tuesday 12/18/2018",
		Time: "7:00pm",
		Location: "River Crest, Rochester Hills, MI",
		Details: "Piano with Justin Jozwiak for holiday party",
	},
	{
		Date: "Sunday 12/16/2018",
		Time: "11:00am - 2:00pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Keyboard and vocals with James O'Donnell",
	},
	{
		Date: "Saturday 12/15/2018",
		Time: "7:00pm",
		Location: "MotorCity Casino, Amnesia",
		Details: "David Thomas &amp; Co. (trio), Private Christmas Party",
	},
	{
		Date: "Sunday 12/9/2018",
		Time: "11:00am - 2:00pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Keyboard and vocals with James O'Donnell",
	},
	{
		Date: "Monday 12/3/2018",
		Time: "1:00pm",
		Location: "Grosse Pointe, MI",
		Details: "Piano and Vocals with the Coachmen; Private Christmas Party",
	},
	{
		Date: "Monday 12/3/2018",
		Time: "8:00pm",
		Location: "MotorCity Casino, Amnesia",
		Details: "David Thomas &amp; Co.: Private Christmas Party",
	},
	{
		Date: "Sunday 12/2/2018",
		Time: "11:00am - 2:00pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Keyboard and vocals with James O'Donnell",
	},
	{
		Date: "Sunday 11/25/2018",
		Time: "11:00am - 2:00pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Keyboard and vocals with James O'Donnell",
	},
	{
		Date: "Wednesday 11/21/2018",
		Time: "2:00pm",
		Location: "IHM Sisters, Monroe, MI",
		Detail:
			"Solo Piano, Vocals, Trumpet, Flute, Piccolo; Private Event for Residents",
	},
	{
		Date: "Sunday 11/18/2018",
		Time: "12:00pm - 3:00pm",
		Location: "Dimitri's Opa! Restaurant &amp; Bar",
		Details: "Keyboard, vocals, and flute with James O'Donnell",
	},
	{
		Date: "Friday 11/16/2018",
		Time: "6:00pm - 9:00pm",
		Location: "The Village of Rochester Hills",
		Detail:
			'David Thomas &amp; Co.; "Light the Village" tree lighting and Santa coming to town ceremony',
	},
	{
		Date: "Sunday 11/11/2018",
		Time: "12:00pm",
		Location: "Sterling Heights, MI",
		Details: "Keyboard with James O'Donnell; Memorial Service music",
	},
	{
		Date: "Saturday 11/3/2018",
		Time: "5:00pm",
		Location: "The Whiskey Factory, Detroit, MI",
		Detail:
			"David Thomas &amp; Co. (Duo) for wedding ceremony and cocktail hour",
	},
	{
		Date: "Sunday 10/28/2018",
		Time: "5:00pm",
		Location: "Sterling Heights, MI",
		Details: "Solo keyboard and vocals for 60th Wedding Anniversary Party",
	},
	{
		Date: "Saturday 10/27/2018",
		Time: "6:00pm",
		Location: "Troy Marriott",
		Detail:
			"Piano, Trumpet, and Flute with Quartet; Wedding cocktail hour and dinner",
	},
	{
		Date: "Saturday 10/27/2018",
		Time: "2:00pm",
		Location: "Blue Goose Inn, St. Clair Shores, MI",
		Detail:
			"Keyboard, vocals, and flute with James O'Donnell; private party",
	},
	{
		Date: "Friday 10/26/2018",
		Time: "6:00pm",
		Location: "Addison Oaks, Leonard, MI",
		Details: "Solo Piano for Wedding Cocktail Hour",
	},
	{
		Date: "Wednesday 10/17/2018",
		Time: "2:00pm",
		Location: "IHM Sisters, Monroe, MI",
		Detail:
			"Solo Piano, Vocals, Trumpet, Flute, Piccolo; Private Event for Residents",
	},
	{
		Date: "Wednesday 10/17/2018",
		Time: "6:00pm - 9:00pm",
		Location: "Detroit",
		Details: "Keyboard with James O'Donnell",
	},
	{
		Date: "Sunday 10/14/2018",
		Time: "1:30pm",
		Location: "Sterling Heights, MI",
		Details: "Friends Supporting Parents Service of Remembrance",
	},
	{
		Date: "Saturday 10/13/2018",
		Time: "",
		Location: "American Polish Century Club, Sterling Heights, MI",
		Details: "Piano with The Coachmen; Private Halloween Party",
	},
	{
		Date: "Friday 10/12/2018",
		Time: "6:00pm",
		Location: "Mirage Hall, Clinton Township, MI",
		Details: "Piano with The Coachmen, MCREST Event",
	},
	{
		Date: "Sunday 10/7/2018",
		Time: "1:00pm",
		Location: "American Polish Century Club, Sterling Heights, MI",
		Detail:
			"Piano and Vocals with the Coachmen; Sweetest Heart of Mary Dinner Dance",
	},
	{
		Date: "Thursday 10/4/2018",
		Time: "6:00pm - 9:00pm",
		Location: "Finnegan's Pub, Rochester Hills, MI",
		Details: "Piano and Vocals with Sheila Landis (Duo)",
	},
	{
		Date: "Saturday 9/29/2018",
		Time: "",
		Location: "Mount Clemens, MI",
		Details: "Memorial Service",
	},
	{
		Date: "Thursday 9/27/2018",
		Time: "6:00pm - 9:00pm",
		Location: "Finnegan's Pub, Rochester Hills, MI",
		Details: "Piano and Vocals with Sheila Landis (Duo)",
	},
	{
		Date: "Saturday 9/22/2018",
		Time: "6:30pm - 9:30pm",
		Location: "Finnegan's Pub, Rochester Hills, MI",
		Details: "Piano and Vocals with Sheila Landis (Duo)",
	},
	{
		Date: "Thursday 9/20/2018",
		Time: "8:00pm - 12:00pm",
		Location: "Cliff Bell's, Detroit, MI",
		Details: "David Thomas &amp; Co. (trio)",
	},
	{
		Date: "Wednesday 9/19/2018",
		Time: "2:00pm",
		Location: "IHM Sisters, Monroe, MI",
		Detail:
			"Solo Piano, Vocals, Trumpet, Flute, Piccolo; Private Event for Residents",
	},
	{
		Date: "Saturday 9/15/2018",
		Time: "6:00pm",
		Location: "The Fieldhouse, Holly, MI",
		Details: "Solo Piano for Wedding Dinner",
	},
	{
		Date: "Sunday 9/9/2018",
		Time: "2:00pm - 7:00pm",
		Location: "St. Louise de Marillac Catholic Church, Warren, MI",
		Details: "Piano with The Coachmen, Festival",
	},
	{
		Date: "Saturday 9/8/2018",
		Time: "6:30pm - 9:30pm",
		Location: "Finnegan's Pub, Rochester Hills, MI",
		Details: "Piano and Vocals with Sheila Landis (Duo)",
	},
	{
		Date: "Friday 8/31/2018",
		Time: "6:00pm",
		Location: "The Village Club, Bloomfield Hills, MI",
		Detail:
			"Solo Piano, Trumpet, and Vocals; Summer Jazz on the Terrace (private)",
	},
	{
		Date: "Thursday 8/23/2018",
		Time: "5:00pm",
		Location: "fleurdetroit",
		Details: "David Thomas &amp; Co., Private Party",
	},
	{
		Date: "Wednesday 8/22/2018",
		Time: "5:30pm",
		Location: " Petruzzello's Banquet and Conference Center, Troy, MI",
		Details: "Solo Piano; Making Strides Against Breast Cancer Fundraiser",
	},
	{
		Date: "Friday 8/17/2018",
		Time: "6:00pm",
		Location: "The Village Club, Bloomfield Hills, MI",
		Details: "Solo Performance - Piano, Trumpet, Vocals",
	},
	{
		Date: "Wednesday 8/15/2018",
		Time: "2:00pm",
		Location: "IHM Sisters, Monroe, MI",
		Detail:
			"Solo Piano, Vocals, Trumpet, Flute, Piccolo; Private Event for Residents",
	},
	{
		Date: "Sunday 8/12/2018",
		Time: "1:00pm",
		Location: "Burton Manor, Livonia, MI",
		Details:
			"Piano and Vocals with The Coachmen, Private Anniversary Party",
	},
	{
		Date: "Saturday 8/11/2018",
		Time: "9:00pm",
		Location: "Duffy's Pub, Auburn Hills, MI",
		Details: "David Thomas &amp; Co. (trio)",
	},
	{
		Date: "Friday 8/10/2018",
		Time: "",
		Location: "Sweetest Heart of Mary Church, Detroit, MI",
		Details: "Piano with The Coachmen, Festival",
	},
	{
		Date: "Saturday 8/4/2018",
		Time: "7:30pm",
		Location: "American Polish Century Club, Sterling Heights, MI",
		Details: "Piano with The Coachmen, Wedding",
	},
	{
		Date: "Saturday 8/4/2018",
		Time: "6:00pm",
		Location: "Schoolcraft College, Livonia, MI",
		Details: "Trio for Special Private Event",
	},
	{
		Date: "Friday 8/3/2018",
		Time: "6:30pm - 9:30pm",
		Location: "Finnegan's Pub, Rochester Hills, MI",
		Details: "Piano and Vocals with Sheila Landis (Duo)",
	},
	{
		Date: "Thursday 7/26/2018",
		Time: "4:30pm - 8:00pm",
		Location: " The Woodhouse Day Spa, The Village of Rochester Hills",
		Details: "Solo Performance for Spa Grand Opening Event",
	},
	{
		Date: "Wednesday 7/18/2018",
		Time: "2:00pm",
		Location: "IHM Sisters, Monroe, MI",
		Detail:
			"Solo Piano, Vocals, Trumpet, Flute, Piccolo; Private Event for Residents",
	},
	{
		Date: "Sunday 7/15/2018",
		Time: "3:30pm - 4:30pm",
		Location: " Michigan Jazz Festival, Schoolcraft College, Livonia, MI",
		Details: "Piano and vocals with Camille Price (duo)",
	},
	{
		Date: "Saturday 7/14/2018",
		Time: "6:30pm - 9:30pm",
		Location: "Finnegan's Pub, Rochester Hills, MI",
		Details: "Piano with Sheila Landis (Duo)",
	},
	{
		Date: "Friday 7/13/2018",
		Time: "6:30pm - 9:30pm",
		Location: "Finnegan's Pub, Rochester Hills, MI",
		Details: "Piano with Sheila Landis (Duo)",
	},
	{
		Date: "Thursday 7/12/2018",
		Time: "7:00pm",
		Location: "Duffy's Pub, Auburn Hills, MI",
		Details: "David Thomas &amp; Co. (Duo)",
	},
	{
		Date: "Thursday 6/28/2018",
		Time: "6:30pm - 9:00pm",
		Location: "Brookedale Woods Subdivision, Rochester Hills, MI",
		Detail:
			"David Thomas &amp; Co. (trio); Concert in the Park on Raintree Drive",
	},
	{
		Date: "Wednesday 6/27/2018",
		Time: "6:00pm",
		Location: "The Village Club, Bloomfield Hills, MI",
		Details: "Solo Performance - Piano, Trumpet, Vocals",
	},
	{
		Date: "Saturday 6/23/2018",
		Time: "2:00pm - 4:00pm",
		Location:
			" The 2018 St. Clair Art Fair, Alice W. Moore Center for the Arts, Saint Clair, MI",
		Details: "Piano, Trumpet, and Vocals with Sheila Landis (Quartet)",
	},
	{
		Date: "Friday 6/22/2018",
		Time: "5:00pm",
		Location: "Bloomfield Hills Country Club",
		Details: "Trio for Special Private Event",
	},
	{
		Date: "Wednesday 6/20/2018",
		Time: "2:00pm",
		Location: "IHM Sisters, Monroe, MI",
		Detail:
			"Solo Piano, Vocals, Trumpet, Flute, Piccolo; Private Event for Residents",
	},
	{
		Date: "Sunday 6/10/2018",
		Time: "7:00pm",
		Location: "Waterford, MI",
		Details: "Piano for Private Event",
	},
	{
		Date: "Saturday 6/9/2018",
		Time: "5:30pm",
		Location: "The Scarab Club, Detroit, MI",
		Details: "Trumpet",
	},
	{
		Date: "Monday 6/4/2018",
		Time: "12:30pm",
		Location: "Grosse Pointe, MI",
		Details: "Piano and vocals with the Coachmen",
	},
	{
		Date: "Thursday 5/31/2018",
		Time: "8:00pm - 12:00pm",
		Location: "Cliff Bell's, Detroit, MI",
		Details: "David Thomas &amp; Co. (trio)",
	},
	{
		Date: "Thursday 5/24/2018",
		Time: "5:00pm",
		Location: "Hugo Boss, Somerset Collection",
		Details: "Solo Piano, Vocals, Trumpet; Sip Into Summer event",
	},
	{
		Date: "Friday 5/18/2018",
		Time: "6:30pm",
		Location: "Finnegan's Pub",
		Details: "Piano with Sheila Landis (Duo)",
	},
	{
		Date: "Wednesday 5/16/2018",
		Time: "3:00pm",
		Location: "IHM Sisters, Monroe, MI",
		Detail:
			"Solo Piano, Vocals, Trumpet, Flute, Piccolo; Private Event for Residents",
	},
	{
		Date: "Thursday 5/10/2018",
		Time: "5:30pm",
		Location: "St. Irenaeus Activities Building, Rochester Hills, MI",
		Detail:
			"Solo Piano and Trumpet for Senior Fellowship Yellow Submarine Supper",
	},
	{
		Date: "Friday 5/4/2018",
		Time: "9:00am",
		Location: "Ojibwa Elementary School, Macomb, MI",
		Details: "School concert with Sean Mallare",
	},
	{
		Date: "Wednesday 4/25/2018",
		Time: "1:45pm - 3:15pm",
		Location: "IHM Sisters, Monroe, MI",
		Details: "Solo Piano for Tea Party",
	},
	{
		Date: "Tuesday 4/24/2018",
		Time: "7:00pm",
		Location: "River Crest, Rochester Hills, MI",
		Details: "Trio for Special Private Event",
	},
	{
		Date: "Wednesday 4/18/2018",
		Time: "3:00pm",
		Location: "IHM Sisters, Monroe, MI",
		Detail:
			"Solo Piano, Vocals, Trumpet, Flute, Piccolo; Private Event for Residents",
	},
	{
		Date: "Thursday 4/12/2018",
		Time: "6:30pm - 7:30pm (1st Set), 8:30pm - 9:30pm (2nd Set)",
		Location: "Dirty Dog Jazz Cafe, Grosse Pointe Farms, MI",
		Details: "David Thomas &amp; Co. (quartet)",
	},
	{
		Date: "Thursday 4/5/2018",
		Time: "6:00pm - 8:00pm",
		Location: "ABeanToGo Coffee, Lake Orion, MI",
		Details: "Solo Piano, Trumpet, and Vocals",
	},
	{
		Date: "Sunday 4/1/2018",
		Time: "10:00am",
		Location: "St. Irenaeus Catholic Church",
		Details: "Trumpet with the church choir for Easter Mass Celebration",
	},
	{
		Date: "Wednesday 3/21/2018",
		Time: "3:00pm",
		Location: "IHM Sisters, Monroe, MI",
		Detail:
			"Solo Piano, Vocals, Trumpet, Flute, Piccolo; Private Event for Residents",
	},
	{
		Date: "Saturday 3/3/2018",
		Time: "6:30pm - 7:30pm (1st Set), 8:30pm - 9:30pm (2nd Set)",
		Location: "Dirty Dog Jazz Cafe, Grosse Pointe Farms, MI",
		Details: "Trumpet and Piccolo with Planet D Nonet",
	},
	{
		Date: "Wednesday 2/21/2018",
		Time: "3:00pm",
		Location: "IHM Sisters, Monroe, MI",
		Detail:
			"Solo Piano, Vocals, Trumpet, Flute, Piccolo; Private Event for Residents",
	},
	{
		Date: "Tuesday 2/13/2018",
		Time: "6:00pm - 10:00pm",
		Location: "Rochester Mills Beer Company",
		Detail:
			"Trumpet and Piccolo - Sitting in with RJ Spangler's Mardi Gras Band",
	},
	{
		Date: "Saturday 2/10/2018",
		Time: "1:00pm - 5:00pm",
		Location: "Hugo Boss, Somerset Collection",
		Detail:
			"Solo Piano, Vocals, Trumpet; Spring Collection Preview with Jazz and Whiskey",
	},
	{
		Date: "Saturday 2/3/2018",
		Time: "9:00pm - 1:00am",
		Location: "Cliff Bell's",
		Details: "Piano and trumpet with the Sheila Landis Trio",
	},
	{
		Date: "Thursday 1/18/2018",
		Time: "7:00pm - 10:00pm",
		Location: "Sweet Lorraine's Lake Tavern, Waterford, MI",
		Details: "Piano with Pam Jaslove",
	},
	{
		Date: "Wednesday 1/17/2018",
		Time: "3:00pm",
		Location: "IHM Sisters, Monroe, MI",
		Detail:
			"Solo Piano, Vocals, Trumpet, Flute, Piccolo; Private Event for Residents",
	},
	{
		Date: "Monday 1/15/2018",
		Time: "5:00pm",
		Location: "American Polish Century Club, Sterling Heights, MI",
		Details: "Piano with The Coachmen",
	},
	{
		Date: "Sunday 12/31/2017",
		Time: "1:30pm - 4:30pm",
		Location: "Assumption Grotto Church",
		Details: "David Thomas &amp; Co. (trio), New Year's Eve Fundraiser",
	},
	{
		Date: "Wednesday 12/20/2017",
		Time: "3:00pm",
		Location: "IHM Sisters, Monroe, MI",
		Detail:
			"Solo Piano, Vocals, Trumpet, Flute, Piccolo; Private Event for Residents",
	},
	{
		Date: "Sunday 12/17/2017",
		Time: "4:00pm - 7:00pm",
		Location: "Blue Goose Inn, St. Clair Shores, MI",
		Details: "Trumpet and Piccolo with Planet D Nonet",
	},
	{
		Date: "Tuesday 12/12/2017",
		Time: "8:00pm",
		Location: "Cadieux Cafe, Detroit, MI",
		Details: "Trumpet and Piccolo with Planet D Nonet",
	},
	{
		Date: "Friday 12/8/2017",
		Time: "6:30pm",
		Location: "San Marino Club, Troy, MI",
		Details: "Trumpet and Piccolo with Planet D Nonet",
	},
	{
		Date: "Thursday 11/30/2017",
		Time: "7:00pm",
		Location: "Vast Kitchen &amp; Bar, Shelby Township, MI",
		Details: "Solo Piano and Vocals",
	},
	{
		Date: "Tuesday 11/28/2017",
		Time: "7:00pm",
		Location: "Rochester Hills, MI",
		Detail:
			"Piano Accompanist, Rochester Community Schools District Children's Choir - Performance",
	},
	{
		Date: "Sunday 11/26/2017",
		Time: "4:00pm - 7:00pm",
		Location: "Blue Goose Inn, St. Clair Shores, MI",
		Details: "Trumpet and Piccolo with Planet D Nonet",
	},
	{
		Date: "Friday 11/24/2017",
		Time: "9:00pm - 1:00am",
		Location: "Cliff Bell's",
		Details: "Trumpet and Piccolo with Planet D Nonet",
	},
	{
		Date: "Thursday 11/16/2017",
		Time: "7:00pm",
		Location: "Vast Kitchen &amp; Bar, Shelby Township, MI",
		Details: "Solo Piano and Vocals",
	},
	{
		Date: "Wednesday 11/15/2017",
		Time: "3:00pm",
		Location: "IHM Sisters, Monroe, MI",
		Detail:
			"Solo Piano, Vocals, Trumpet, Flute, Piccolo; Private Event for Residents",
	},
	{
		Date: "Friday 11/3/2017",
		Time: "6:00pm",
		Location: "Royalty House, Warren, MI",
		Detail:
			"Wedding Cocktail Hour and Dinner - David Thomas &amp; Co. (Quartet)",
	},
	{
		Date: "Thursday 11/2/2017",
		Time: "7:00pm",
		Location: "Vast Kitchen &amp; Bar, Shelby Township, MI",
		Details: "Solo Piano and Vocals",
	},
	{
		Date: "Sunday 10/29/2017",
		Time: "4:00pm - 7:00pm",
		Location: "Blue Goose Inn, St. Clair Shores, MI",
		Details: "Trumpet and Piccolo with Planet D Nonet",
	},
	{
		Date: "Thursday 10/26/2017",
		Time: "5:00pm",
		Location: "Madison Heights Senior Ctr.",
		Details: "Piano with Paul Parente",
	},
	{
		Date: "Sunday 10/22/2017",
		Time: "",
		Location: "American Polish Century Club, Sterling Heights, MI",
		Details: "Piano with The Coachmen, Dinner/Dance",
	},
	{
		Date: "Saturday 10/21/2017",
		Time: "7:00pm",
		Location: "Vast Kitchen &amp; Bar, Shelby Township, MI",
		Details: "Solo Piano and Vocals",
	},
	{
		Date: "Wednesday 10/18/2017",
		Time: "3:00pm",
		Location: "IHM Sisters, Monroe, MI",
		Detail:
			"Solo Piano, Vocals, Trumpet, Flute, Piccolo; Private Event for Residents",
	},
	{
		Date: "Friday 10/13/2017",
		Time: "7:00pm - 11:00pm",
		Location: "Mirage Hall, Clinton Township, MI",
		Details: "Piano with The Coachmen, MCREST Event",
	},
	{
		Date: "Sunday 10/8/2017",
		Time: "1:30pm - 3:30pm",
		Location: "Sterling Heights, MI",
		Details: "Friends Supporting Parents Service of Remembrance",
	},
	{
		Date: "Sunday 10/8/2017",
		Time: "4:00pm - 7:00pm",
		Location: "Vast Kitchen &amp; Bar, Shelby Township, MI",
		Details: "Solo Piano and Vocals, Private Event",
	},
	{
		Date: "Thursday 10/5/2017",
		Time: "7:00pm",
		Location: "Vast Kitchen &amp; Bar, Shelby Township, MI",
		Details: "Solo Piano and Vocals",
	},
	{
		Date: "Thursday 9/28/2017",
		Time: "7:00pm",
		Location: "The Whisky Parlor",
		Details: "Piano with James O'Donnell",
	},
	{
		Date: "Sunday 9/24/2017",
		Time: "4:00pm - 7:00pm",
		Location: "Blue Goose Inn, St. Clair Shores, MI",
		Details: "Trumpet and Piccolo with Planet D Nonet",
	},
	{
		Date: "Friday 9/22/2017",
		Time: "7:00pm",
		Location: "Vast Kitchen &amp; Bar, Shelby Township, MI",
		Details: "Solo Piano and Vocals",
	},
	{
		Date: "Thursday 9/21/2017",
		Time: "7:00pm",
		Location: "The Whisky Parlor",
		Details: "Piano with James O'Donnell",
	},
	{
		Date: "Sunday 9/17/2017",
		Time: "2:00pm",
		Location: "Clinton Township, MI",
		Details: "David Thomas &amp; Co., Anniversary Party",
	},
	{
		Date: "Saturday 9/16/2017",
		Time: "9:00pm - 12:00am",
		Location: "The Whisky Parlor",
		Details: "Piano with James O'Donnell",
	},
	{
		Date: "Friday 9/15/2017",
		Time: "8:00pm - 10:00pm",
		Location: "Farmington Civic Theater",
		Detail:
			"Solo Rhodes electric piano, flute, vocals; Opening for The Sheila Landis Trio",
	},
	{
		Date: "Thursday 9/14/2017",
		Time: "7:00pm",
		Location: "The Whisky Parlor",
		Details: "Piano with James O'Donnell",
	},
	{
		Date: "Sunday 9/10/2017",
		Time: "3:00pm - 7:00pm",
		Location: "St. Louise de Marillac Catholic Church, Warren, MI",
		Details: "Piano with The Coachmen, Festival",
	},
	{
		Date: "Saturday 9/9/2017",
		Time: "7:00pm",
		Location: "Vast Kitchen &amp; Bar, Shelby Township, MI",
		Details: "Solo Piano and Vocals",
	},
	{
		Date: "Thursday 9/7/2017",
		Time: "7:00pm",
		Location: "The Whisky Parlor",
		Details: "Piano with James O'Donnell",
	},
	{
		Date: "Saturday 9/2/2017",
		Time: "9:00pm",
		Location: "Mint 29, Dearborn, MI",
		Details: "Trumpet and Piccolo with Planet D Nonet",
	},
	{
		Date: "Saturday 8/26/2017",
		Time: "6:00pm - 10:00pm",
		Location: "Rochester Hills, MI",
		Details: "Private Event - Piano with James O'Donnell",
	},
	{
		Date: "Wednesday 8/23/2017",
		Time: "3:00pm",
		Location: "American House, Rochester Hills, MI",
		Details: "Solo Piano",
	},
	{
		Date: "Wednesday 8/23/2017",
		Time: "6:30pm - 9:30pm",
		Location: "The Rec Bowl, Mt. Clemens, MI",
		Details: "Trumpet with Planet D Nonet",
	},
	{
		Date: "Saturday 8/19/2017",
		Time: "4:00pm",
		Location: "Detroit Repertory Theater Arts Fair, Detroit, MI",
		Details: "Trumpet and Piccolo with Planet D Nonet",
	},
	{
		Date: "Saturday 8/19/2017",
		Time: "7:00pm - 10:00pm",
		Location: "St. Clair Shores, MI",
		Details: "Trumpet and Piccolo with Planet D Nonet, Private Party",
	},
	{
		Date: "Thursday 8/17/2017",
		Time: "8:30pm - 11:30pm",
		Location: "Summer Swing Spectacular, Farmington, MI",
		Details: "Trumpet and Piccolo with Planet D Nonet",
	},
	{
		Date: "Friday 8/11/2017",
		Time: "6:00pm - 10:00pm",
		Location: "Sweetest Heart of Mary Church, Detroit, MI",
		Details: "Piano with The Coachmen, Pierogi Festival",
	},
	{
		Date: "Sunday 8/6/2017",
		Time: "7:00pm - 11:00pm",
		Location: "Gull Landing, Pentwater, MI",
		Details: "Trumpet with Planet D Nonet - Scully Tour",
	},
	{
		Date: "Saturday 8/5/2017",
		Time: "7:00pm - 9:15pm",
		Location: "Wenger Pavilion, Baldwin, MI",
		Details: "Trumpet with Planet D Nonet - Scully Tour",
	},
	{
		Date: "Friday 8/4/2017",
		Time: "7:00pm - 9:15pm",
		Location: "Rambat Band Shell, Reed City, MI",
		Details: "Trumpet with Planet D Nonet - Scully Tour",
	},
	{
		Date: "Thursday 8/3/2017",
		Time: "7:00pm - 9:15pm",
		Location: "Rotary Band Shell, Cadillac, MI",
		Details: "Trumpet with Planet D Nonet - Scully Tour",
	},
	{
		Date: "Wednesday 8/2/2017",
		Time: "7:00pm - 11:00pm",
		Location: "Gull Landing, Pentwater, MI",
		Details: "Trumpet with Planet D Nonet - Scully Tour",
	},
	{
		Date: "Tuesday 8/1/2017",
		Time: "7:00pm - 9:15pm",
		Location: "First Street Beach, Manistee, MI",
		Details: "Trumpet with Planet D Nonet - Scully Tour",
	},
	{
		Date: "Monday 7/31/2017",
		Time: "7:00pm",
		Location: "Wahby Park, St. Clair Shores, MI",
		Details: "Trumpet with Planet D Nonet",
	},
	{
		Date: "Thursday 7/27/2017",
		Time: "6:30pm - 8:30pm",
		Location: "The Village of Rochester Hills (Gazebo)",
		Details: "David Thomas &amp; Co. (trio)",
	},
	{
		Date: "Wednesday 7/26/2017",
		Time: "6:30pm - 9:30pm",
		Location: "The Rec Bowl, Mt. Clemens, MI",
		Details: "Trumpet with Planet D Nonet",
	},
	{
		Date: "Thursday 7/20/2017",
		Time: "6:15pm",
		Location: "American Polish Century Club, Sterling Heights, MI",
		Details: "Piano with Darryl Onderik, Birthday Party for Chuck Willard",
	},
	{
		Date: "Saturday 7/15/2017",
		Time: "8:00pm - 11:00pm",
		Location: "Mt. Clemens, MI",
		Details: "Piano with The Coachmen, Wedding",
	},
	{
		Date: "Saturday 7/8/2017",
		Time: "2:00pm",
		Location: " Lakeland Banquet &amp; Event Centre, St. Clair Shores, MI",
		Details: "Piano with Darryl Onderik",
	},
	{
		Date: "Friday 7/7/2017",
		Time: "12:30pm",
		Location: "American House, Rochester Hills, MI",
		Details: "Solo Piano for Independence Day Event",
	},
	{
		Date: "Saturday 7/1/2017",
		Time: "6:45pm",
		Location: "Rochester Chop House, Kabin Kruser's Oyster Bar",
		Details: "Solo Piano",
	},
	{
		Date: "Wednesday 6/28/2017",
		Time: "6:30pm - 9:30pm",
		Location: "The Rec Bowl, Mt. Clemens, MI",
		Details: "Trumpet with Planet D Nonet",
	},
	{
		Date: "Sunday 6/25/2017",
		Time: "11:30am",
		Location: "St. Irenaeus Catholic Church",
		Details: "Trumpet for St. Irenaeus' 50th Anniversary Celebration",
	},
	{
		Date: "Sunday 6/18/2017",
		Time: "6:00pm - 8:00pm",
		Location: "Cultivate Coffee &amp; Tap House",
		Details: "Trumpet with Planet D Nonet",
	},
	{
		Date: "Saturday 6/17/2017",
		Time: "8:00pm - 11:00pm",
		Location: "Rochester Tap Room",
		Details: "David Thomas &amp; Co. (trio)",
	},
	{
		Date: "Saturday 6/10/2017",
		Time: "2:00pm",
		Location: "St. Irenaeus Catholic Church",
		Details: "Wedding Ceremony - Trumpet with Cliff Wilkins",
	},
	{
		Date: "Friday 6/2/2017",
		Time: "9:30pm - 1:30am",
		Location: "Bostonz Bar &amp; Grill, Eastpointe, MI",
		Details: "David Thomas &amp; Co. (trio)",
	},
	{
		Date: "Saturday 5/27/2017",
		Time: "7:00pm - 10:00pm",
		Location: "ABeanToGo Coffee, Lake Orion, MI",
		Details: "Solo Piano and Vocals",
	},
	{
		Date: "Saturday 5/20/2017",
		Time: "2:30pm",
		Location: "American Polish Century Club, Sterling Heights, MI",
		Details: "Piano with Darryl Onderik, Private Birthday Party",
	},
	{
		Date: "Thursday 5/11/2017",
		Time: "2:00pm - 3:00pm",
		Location: "IHM Sisters, Monroe, MI",
		Details: "Piano with Darryl Onderik and Michael Carluccio",
	},
	{
		Date: "Thursday 4/20/2017",
		Time: "6:00pm - 8:00pm",
		Location: "ABeanToGo Coffee, Lake Orion, MI",
		Details: "Solo Piano and Vocals",
	},
	{
		Date: "Sunday 4/16/2017",
		Time: "9:45am",
		Location: "St. Irenaeus Catholic Church",
		Details: "Trumpet with the church choir for Easter Mass Celebration",
	},
	{
		Date: "Friday 3/10/2017",
		Time: "7:00pm - 10:00pm",
		Location: "ABeanToGo Coffee, Lake Orion, MI",
		Details: "Solo Piano",
	},
	{
		Date: "Thursday 3/2/2017",
		Time: "7:00pm - 10:00pm",
		Location: "Vast Kitchen &amp; Bar, Shelby Township, MI",
		Details: "Solo Piano",
	},
	{
		Date: "Tuesday 2/28/2017",
		Time: "6:00pm - 10:00pm",
		Location: "Rochester Mills Beer Company",
		Detail:
			"Sitting in with RJ Spangler and James O'Donnell - Mardi Gras Celebration",
	},
	{
		Date: "Tuesday 2/14/2017",
		Time: "5:45pm",
		Location: "Sunrise Senior Living",
		Details: "Solo Piano for Valentine's Day Event",
	},
	{
		Date: "Thursday 2/9/2017",
		Time: "7:00pm - 10:00pm",
		Location: "Vast Kitchen &amp; Bar, Shelby Township, MI",
		Details: "Solo Piano",
	},
	{
		Date: "Thursday 1/19/2017",
		Time: "6:00pm - 8:00pm",
		Location: "ABeanToGo Coffee, Lake Orion, MI",
		Details: "Solo Piano",
	},
	{
		Date: "Monday 1/16/2017",
		Time: "7:00pm",
		Location: "American Polish Century Club, Sterling Heights, MI",
		Detail:
			"Fundraiser for American Cancer Fund - piano with James O'Donnell",
	},
	{
		Date: "Saturday 12/31/2016",
		Time: "7:30pm",
		Location: "Assumption Grotto Church",
		Detail:
			"New Year's Eve Church Fundraiser Dance - David Thomas &amp; Co.",
	},
	{
		Date: "Thursday 12/15/2016",
		Time: "7:00pm",
		Location: "Reuther Middle School, Rochester Hills, MI",
		Detail:
			"Piano Accompanist, Rochester Community Schools District Children's Choir - Reuther Winter Choir Concert",
	},
	{
		Date: "Saturday 12/10/2016",
		Time: "6:00pm",
		Location: "Ann Arbor Art Center",
		Detail:
			"Private Christmas Party - Piano and Trumpet with James O'Donnell and Mario Rodriguez",
	},
	{
		Date: "Thursday 12/8/2016",
		Time: "7:00pm",
		Location: "Rochester Adams High School",
		Detail:
			"Piano Accompanist, Rochester Community Schools District Children's Choir - Rochester Adams Winter Band Concert",
	},
	{
		Date: "Saturday 12/3/2016",
		Time: "6:30pm",
		Location: "The Dearborn Inn, Dearborn, MI",
		Details: "Solo Piano for Private Wedding Reception",
	},
	{
		Date: "Saturday 11/19/2016",
		Time: "9:00pm - 1:00am",
		Location: "Village Grille, Grosse Pointe, MI",
		Details: "Piano with James O'Donnell",
	},
	{
		Date: "Thursday 11/17/2016",
		Time: "4:45pm - 6:15pm",
		Location: "Sunrise Senior Living",
		Details: "Solo Piano for Thanksgiving Dinner Event",
	},
	{
		Date: "Thursday 11/17/2016",
		Time: "6:45pm",
		Location: "Charter Township of Oakland Clerk's Office",
		Details: "Solo Piano for Private Swearing-In Ceremony",
	},
	{
		Date: "Saturday 11/5/2016",
		Time: "9:00pm",
		Location: "Duffy's Pub - Auburn Hills",
		Details: "David Thomas &amp; Co.",
	},
	{
		Date: "Saturday 10/22/2016",
		Time: "9:00pm - 1:00am",
		Location: "Village Grille, Grosse Pointe, MI",
		Details: "Piano with James O'Donnell",
	},
	{
		Date: "Thursday 10/13/2016",
		Time: "6:30pm - 7:30pm",
		Location: "Ray Township Library",
		Details: "Piano and Discussion for Children's Music Program",
	},
	{
		Date: "Saturday 10/8/2016",
		Time: "7:00pm",
		Location: "Romeo Masonic Temple",
		Details: "Trumpet with Planet D Nonet",
	},
	{
		Date: "Saturday 10/1/2016",
		Time: "9:00pm",
		Location: "Duffy's Pub - Auburn Hills",
		Details: "David Thomas &amp; Co.",
	},
	{
		Date: "Saturday 9/17/2016",
		Time: "7:00pm - 11:00pm",
		Location: "J. Baldwin's Restaurant",
		Details: "Piano with Kathleen Sabino",
	},
	{
		Date: "Sunday 9/11/2016",
		Time: "12:00pm",
		Location: "Sunrise Senior Living",
		Details: "Solo Piano for Grandparents Day Event",
	},
	{
		Date: "Saturday 9/10/2016",
		Time: "6:00pm - 9:00pm",
		Location: "Wellers, Saline, MI",
		Details: "Private Wedding - Piano and trumpet with James O'Donnell",
	},
	{
		Date: "Friday 9/9/2016",
		Time: "7:00pm - 11:00pm",
		Location: "Belleville Yacht Club",
		Details: "Trumpet with Planet D Nonet - Benefit Event",
	},
	{
		Date: "Saturday 9/3/2016",
		Time: "2:00pm",
		Location: "Livonia, MI",
		Details: "Private Wedding - Piano",
	},
	{
		Date: "Friday 8/19/2016",
		Time: "",
		Location: "Waterford, MI",
		Details: "Private Wedding - David Thomas and Company",
	},
	{
		Date: "Wednesday 8/17/2016",
		Time: "6:00pm - 9:00pm",
		Location: "The Rec Bowl, Mt. Clemens, MI",
		Details: "Trumpet with Planet D Nonet",
	},
	{
		Date: "Saturday 8/13/2016",
		Time: "9:00pm",
		Location: "Duffy's Pub - Auburn Hills",
		Details: "David Thomas &amp; Co.",
	},
	{
		Date: "Friday 8/12/2016",
		Time: "6:45pm",
		Location: "Rochester Chop House, Kabin Kruser's Oyster Bar",
		Details: "Solo Piano",
	},
	{
		Date: "Thursday 8/11/2016",
		Time: "6:45pm",
		Location: "Rochester Chop House, Kabin Kruser's Oyster Bar",
		Details: "Solo Piano",
	},
	{
		Date: "Saturday 8/6/2016",
		Time: "7:00pm - 11:00pm",
		Location: "J. Baldwin's Restaurant",
		Details: "Piano with Kathleen Sabino",
	},
	{
		Date: "Friday 8/5/2016",
		Time: "6:00pm",
		Location: "Kimball, MI",
		Details: "Private Wedding - Piano",
	},
	{
		Date: "Sunday 7/31/2016",
		Time: "7:00pm - 11:00pm",
		Location: "Gull Landing - Pentwater, MI",
		Details: "Trumpet with Planet D Nonet - Scully Tour",
	},
	{
		Date: "Saturday 7/30/2016",
		Time: "7:00pm - 9:15pm",
		Location: "Wenger Pavilion - Baldwin, MI",
		Details: "Trumpet with Planet D Nonet - Scully Tour",
	},
	{
		Date: "Friday 7/29/2016",
		Time: "7:00pm - 9:15pm",
		Location: "Rambat Band Shell - Reed City, MI",
		Details: "Trumpet with Planet D Nonet - Scully Tour",
	},
	{
		Date: "Thursday 7/28/2016",
		Time: "7:00pm - 9:15pm",
		Location: "Rotary Band Shell - Cadillac, MI",
		Details: "Trumpet with Planet D Nonet - Scully Tour",
	},
	{
		Date: "Wednesday 7/27/2016",
		Time: "7:00pm - 11:00pm",
		Location: "Gull Landing - Pentwater, MI",
		Details: "Trumpet with Planet D Nonet - Scully Tour",
	},
	{
		Date: "Tuesday 7/26/2016",
		Time: "7:00pm - 9:15pm",
		Location: "First Street Beach Pavilion - Manistee, MI",
		Details: "Trumpet with Planet D Nonet - Scully Tour",
	},
	{
		Date: "Saturday 7/23/2016",
		Time: "6:45pm",
		Location: "Rochester Chop House, Kabin Kruser's Oyster Bar",
		Details: "Solo Piano",
	},
	{
		Date: "Thursday 7/21/2016",
		Time: "7:00pm",
		Location: "Duffy's Pub - Auburn Hills",
		Details: "David Thomas and Sam Copperman Duo",
	},
	{
		Date: "Thursday 7/14/2016",
		Time: "7:00pm",
		Location: "Duffy's Pub - Auburn Hills",
		Details: "David Thomas and Sam Copperman Duo",
	},
	{
		Date: "Saturday 7/9/2016",
		Time: "6:45pm",
		Location: "Rochester Chop House, Kabin Kruser's Oyster Bar",
		Details: "Solo Piano",
	},
	{
		Date: "Saturday 7/2/2016",
		Time: "6:45pm",
		Location: "Rochester Chop House, Kabin Kruser's Oyster Bar",
		Details: "Solo Piano",
	},
	{
		Date: "Saturday 6/18/2016",
		Time: "4pm - 10pm",
		Location: "Hilltop Brewery",
		Details: "Private Event - David Thomas and Company",
	},
	{
		Date: "Friday 6/17/2016",
		Time: "4pm - 10pm",
		Location: "Hilltop Brewery",
		Details: "Private Event - David Thomas and Company",
	},
	{
		Date: "Saturday 6/11/2016",
		Time: "9:00pm",
		Location: "Duffy's Pub - Auburn Hills",
		Details: "David Thomas and Company",
	},
	{
		Date: "Tuesday 5/31/2016",
		Time: "7:00pm - 10:00pm",
		Location: "Plymouth-Ann Arbor Elks 325",
		Details: "Trumpet with Planet D Nonet",
	},
	{
		Date: "Thursday 5/19/2016",
		Time: "7:00pm",
		Location: "Duffy's Pub - Auburn Hills",
		Details: "David Thomas and Sam Copperman Duo",
	},
	{
		Date: "Saturday 5/7/2016",
		Time: "11:30am",
		Location: "Sunrise Senior Living",
		Details: "Solo Piano for Mother's Day Event",
	},
	{
		Date: "Saturday 4/23/2016",
		Time: "9:00pm",
		Location: "Duffy's Pub - Auburn Hills",
		Details: "David Thomas and Company",
	},
	{
		Date: "Friday 4/22/2016",
		Time: "6:45pm",
		Location: "Rochester Chop House, Kabin Kruser's Oyster Bar",
		Details: "Solo Piano",
	},
	{
		Date: "Thursday 3/31/2016",
		Time: "7:00pm - 11:00pm",
		Location: "Duffy's Pub - Auburn Hills",
		Details: "David Thomas and Company - Duo with Sam Copperman",
	},
	{
		Date: "Sunday 3/27/2016",
		Time: "10:00am",
		Location: "St. Irenaeus Catholic Church",
		Details: "Trumpet with the church choir for Easter Mass Celebration",
	},
	{
		Date: "Friday 3/25/2016",
		Time: "6:45pm",
		Location: "Rochester Chop House / Kabin Kruser's Oyster Bar",
		Details: "Solo piano",
	},
	{
		Date: "Tuesday 3/15/2016",
		Time: "5:00pm",
		Location: "Rochester High School",
		Detail:
			"Piano Accompanist, Rochester Community Schools District Children's Choir - RCS Elementary Choral Festival",
	},
	{
		Date: "Thursday 3/10/2016",
		Time: "7:00pm - 11:00pm",
		Location: "Duffy's Pub - Auburn Hills",
		Details: "David Thomas and Company - Duo with Sam Copperman",
	},
	{
		Date: "Monday 3/7/2016",
		Time: "6:30pm",
		Location: "Rochester High School",
		Detail:
			"Piano Accompanist, Rochester Community Schools District Children's Choir - Rochester High School Choir Concert",
	},
	{
		Date: "Thursday 3/3/2016",
		Time: "7:00pm",
		Location: "Rochester High School",
		Detail:
			"Piano Accompanist, Rochester Community Schools District Children's Choir - Founder's Day Program",
	},
	{
		Date: "Wednesday 2/17/2016",
		Time: "7:00pm",
		Location: "Stray Cat Lounge",
		Details: "Featured Artist Series",
	},
	{
		Date: "Sunday 2/14/2016",
		Time: "6:00pm",
		Location: "Sunrise Senior Living",
		Details: "Valentine's Day Party",
	},
	{
		Date: "Wednesday 1/27/2016",
		Time: "6:00pm - 8:30pm",
		Location: "Eisenhower High School",
		Details: "Jazz Clinic",
	},
	{
		Date: "Saturday 1/16/2016",
		Time: "9:00pm - 1:00am",
		Location: "Duffy's Pub - Auburn Hills, MI",
		Details: "David Thomas &amp; Company",
	},
	{
		Date: "Thursday 12/31/2015",
		Time: "6:45pm - 11:30pm",
		Location: "Rochester Chop House",
		Details: "Solo Piano",
	},
	{
		Date: "Thursday 12/24/2015",
		Time: "6:45pm - 8pm",
		Location: "Rochester Chop House",
		Details: "Solo Piano",
	},
	{
		Date: "Friday 12/18/2015",
		Time: "6:00pm",
		Location: "Lelli's - Auburn Hills",
		Details: "Private Christmas Party",
	},
	{
		Date: "Saturday 12/5/2015",
		Time: "6:30pm",
		Location: "MSU Detroit Center",
		Details: "Community Music School",
	},
	{
		Date: "Saturday 11/21/2015",
		Time: "6:45pm - 11:30pm",
		Location: "Rochester Chop House - Rochester, MI",
		Details: "Solo Piano",
	},
	{
		Date: "Sunday 9/27/2015",
		Time: "2:00pm",
		Location: "Hawk Hollow Chapel, Bath Township, MI",
		Details: "Naeyaert Wedding - Piano",
	},
];
